config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do     #users/user_id/followingとかになる       memberじゃなくて collectionやったらidで区別しない
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]#user認証（リンクを踏むだけやからeditで！）
  resources :password_resets,     only: [:new, :create, :edit, :update]#PW再設定
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :likes, only: [:index, :create, :destroy]
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes

  mount_uploader :picture, PictureUploader
  default_scope -> { order(created_at: :desc) } #デフォルtの取り出しを照準に
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validate  :picture_size

  private

  # アップロードされた画像のサイズをバリデーションする
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end


end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_back(fallback_location: root_url)
  end

  private

    def micropost_params
      params.require(:micropost).permit(:content, :picture)
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
    <%= micropost.content %>
    <%= image_tag micropost.picture.url if micropost.picture? %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    いいね<span class="like_count"><%= micropost.likes.count %></span>件
    <% if current_user?(micropost.user) %>
      <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% else %>
      <% if micropost.likes.find_by(user_id: current_user.id)%>
        <%= form_with url: like_path(micropost.likes.find_by(user_id: current_user.id).id), method: :delete, class: "unlike-form" do |f| %>
          <%= f.hidden_field :micropost_id, value: micropost.id, class: "m_f" %>
          <%= f.submit "いいね解除", class: "unlike-bo" %>
        <% end %>
      <% else %>
        <%= form_with url: likes_path,class:"like-form", local: true do |f| %>
          <%= f.hidden_field :micropost_id, value: micropost.id, class: "m_f" %>
          <%= f.submit "いいね！", class: "like-bo"%>
        <% end %>
      <% end %>
    <% end %>
  </span>
</li>